### ISSUE TITLE
Dependency tree is... well... insane

### ISSUE THREAD

**Issue by broofa** [robotomize/correlation-rank-js#1]
`npm install --production correlation-rank` installs a ridiculous amount of modules.  Consider removing the dependency on babel?

See http://npm.broofa.com/?q=correlation-rank

**Comment by robotomize** [comment]
U right, ok, but I don't understand why it is not working now. I do not have regular dependencies in the package.json. Why installed dev dependencies cannot understand.

**Comment by robotomize** [comment]
Fix in this revision, closed

**Comment by broofa** [comment]
Thanks!
